
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 25 15:18:41 EET 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASSIGN_OP = 13;
  public static final int EXCEPT = 38;
  public static final int COMP_OP = 11;
  public static final int STR = 3;
  public static final int CONTINUE = 39;
  public static final int BITWISE_OP = 14;
  public static final int FOR = 32;
  public static final int ID_OP = 16;
  public static final int LS = 4;
  public static final int IN = 28;
  public static final int BOOL = 9;
  public static final int COMMA = 27;
  public static final int RS = 5;
  public static final int ARTH_OP = 10;
  public static final int NUM = 18;
  public static final int IF = 29;
  public static final int DOT = 19;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int LC = 20;
  public static final int LB = 22;
  public static final int error = 1;
  public static final int RC = 21;
  public static final int RB = 23;
  public static final int LOGICAL_OP = 12;
  public static final int SMCOL = 24;
  public static final int NEWLINE = 6;
  public static final int TRY = 37;
  public static final int BREAK = 40;
  public static final int KW = 2;
  public static final int FROM = 34;
  public static final int IMPORT = 35;
  public static final int COL = 25;
  public static final int ELSE = 30;
  public static final int WHILE = 33;
  public static final int DEDENT = 8;
  public static final int MEM_OP = 15;
  public static final int DEF = 36;
  public static final int AT = 26;
  public static final int INDENT = 7;
  public static final int ELIF = 31;
}

